## Course Assignment Instructions
You should have Python (version 3.8 or later) and Jupyter Notebook installed to complete this assignment. You will write code in the empty cell/cells below the problem. While most of this will be a programming assignment, some questions will ask you to "write a few sentences" in markdown cells. 

Submission Instructions:

Create a labs directory in your personal class repository (e.g., located in your home directory)
Clone the class repository
Copy this Jupyter notebook file (.ipynb) into your repo/labs directory
Make your edits, commit changes, and push to your repository
All submissions must be pushed before the due date to avoid late penalties

* Install the numpy, scipy, statsmodels, and pandas packages (we will be using these throughout the semester)

In [138]:
import numpy as np
import pandas as pd
import statsmodels as sm
import scipy as sp

* Print out the numerical constant pi with ten digits after the decimal point using constant 'pi'. You will need to use the math module in python for this. 

In [139]:
import math
round(math.pi, 10)

3.1415926536

* Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ... use base python

In [140]:
terms = [1]*103
for i in range(1, len(terms)):
    terms[i]=terms[i-1]/2

sum(terms)

2.0

using numpy

In [141]:
np.sum(np.geomspace(1,2**(-102),103, endpoint=True))
total = np.sum(1/(2**i) for i in np.arange(103))
total

C:\Users\sneeky\AppData\Local\Temp\ipykernel_14516\2925419549.py:2: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  total = np.sum(1/(2**i) for i in np.arange(103))
C:\Users\sneeky\AppData\Local\Temp\ipykernel_14516\2925419549.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  total = np.sum(1/(2**i) for i in np.arange(103))


inf

 * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.  * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.

* Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

using base python

In [142]:
prod=1
temp=1

for i in range(387):
    prod*=temp
    temp/=2

prod

0.0

using numpy

In [143]:
np.prod(np.geomspace(1,2**(-386),387, endpoint=True))

0.0

Is this answer *exactly* correct?

No, this answer is not exactly correct. The number should be positive although very small and the answer generated is a result of numerical underflow.

* Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [144]:
from fractions import Fraction

log_prod=0
d=1

for i in range(387):
    temp=Fraction(1,d)
    log_prod+=math.log(temp, 2)
    d*=2

print("log base 2 answer is", log_prod)

log base 2 answer is -74691.0


* using numpy ... Hint: use the `log` and `sum` functions in numpy

In [145]:
exponent=np.sum(np.arange(387))*-1
print("log base 2 answer is", exponent)

log base 2 answer is -74691


* Create the sequence `x = [Inf, 20, 18, ..., -20]`.

Pure python

In [146]:
# Create the sequence
x = [float('inf')] + list(range(20, -21, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


Using numpy

In [147]:
# Create the sequence
x = [float('inf')] + list(np.arange(20, -22, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


*   Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]` ... Use `log` from numpy.

In [148]:
sequence=[float('inf')] + list(range(100,-21,-2))
x = np.log(sequence)/np.log(3)
x

C:\Users\sneeky\AppData\Local\Temp\ipykernel_14516\1185925641.py:2: RuntimeWarning: divide by zero encountered in log
  x = np.log(sequence)/np.log(3)
C:\Users\sneeky\AppData\Local\Temp\ipykernel_14516\1185925641.py:2: RuntimeWarning: invalid value encountered in log
  x = np.log(sequence)/np.log(3)


array([       inf, 4.19180655, 4.17341725, 4.15464877, 4.13548513,
       4.11590934, 4.09590327, 4.0754476 , 4.05452164, 4.03310326,
       4.01116872, 3.98869254, 3.96564727, 3.94200337, 3.91772888,
       3.89278926, 3.86714702, 3.84076143, 3.81358809, 3.78557852,
       3.75667961, 3.72683303, 3.69597451, 3.66403301, 3.63092975,
       3.59657703, 3.5608768 , 3.52371901, 3.48497958, 3.44451785,
       3.4021735 , 3.35776278, 3.31107361, 3.26185951, 3.20983168,
       3.15464877, 3.09590327, 3.03310326, 2.96564727, 2.89278926,
       2.81358809, 2.72683303, 2.63092975, 2.52371901, 2.4021735 ,
       2.26185951, 2.09590327, 1.89278926, 1.63092975, 1.26185951,
       0.63092975,       -inf,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan])

* Create a vector of booleans where the entry is true if `x[i]` is positive and finite. Use `&` from base python along with `isnan` and `isinfinite` from numpy

In [153]:
y = ~np.isnan(x) & np.isfinite(x) & (x > 0)
print(y)

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False]


* Locate the indices of the non-real numbers in this vector. Numpy has a `where` function in lieu of R's `which`

In [152]:
false_indices=np.where(y==False)[0]
print(false_indices)

[ 0 51 52 53 54 55 56 57 58 59 60 61]


* Locate the indices of the infinite quantities in this vector using `where` and `isinf` from numpy.

In [154]:
infin_indices=np.where(np.isinf(x))[0]
print(infin_indices)

[ 0 51]


* Locate the indices of the min and max in this vector. Hint: use the `arg.min` and `arg.max` functions from numpy

In [155]:
xs=[i for i in x if(~np.isnan(i))]
print(np.argmin(xs))
print(np.argmax(xs))

51
0


* Count the number of unique values in `x`. Use `unique` from numpy.

In [158]:
print(len(np.unique(x)))

53


* Cast `x` to a factor. Do the number of levels make sense? Should be 53 unique values. Use `categorical` from pandas.

In [159]:
# Cast x to a categorical (similar to as.factor(x) in R)
x_factor = pd.Categorical(x)

# Check the unique levels (categories)
levels = x_factor.categories
num_levels = len(levels)

print(f"Factor levels: {levels}")
print(f"Number of levels: {num_levels}")

Factor levels: Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.0545216380691365, 

* In Python, using pandas, NaN is not treated as a level in a categorical type by default. Pandas does not allow NaN to be a category. To include NaN as a level, you need to explicitly handle it by filling them with a placeholder value (like "NaN" or a specific number) before making the data categorical. Use `categorical` and `isna` from pandas.

In [160]:
# Replace NaN with a placeholder value (e.g., 'NaN')
x_filled = [val if not pd.isna(val) else 'NaN' for val in x] #list comprehension

# Convert to categorical
x_factor = pd.Categorical(x_filled)

# Check the unique levels (including 'NaN' as a level)
factor_levels = x_factor.categories
num_levels = len(factor_levels)

print(f"Factor levels (including NaN): {factor_levels}")
print(f"Number of levels: {num_levels}")

Factor levels (including NaN): Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.05

* Cast `x` to integers. Use `where`, `isinfinite` from numpy and `astype` from base python.

In [162]:
replaced_inf = np.where(np.isfinite(x), x,0)
int_replace = replaced_inf.astype(int)
print(int_replace)

[0 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 2 2 2 2 2 2 2 2 2 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]


* Use `x` to create a new vector `y` containing only the real numbers in x. Use `isnan`, `logical_and`, and `reduce` from numpy

In [163]:
y=x[np.logical_and.reduce((~np.isnan(x), np.isfinite(x), x>0))]
y


array([4.19180655, 4.17341725, 4.15464877, 4.13548513, 4.11590934,
       4.09590327, 4.0754476 , 4.05452164, 4.03310326, 4.01116872,
       3.98869254, 3.96564727, 3.94200337, 3.91772888, 3.89278926,
       3.86714702, 3.84076143, 3.81358809, 3.78557852, 3.75667961,
       3.72683303, 3.69597451, 3.66403301, 3.63092975, 3.59657703,
       3.5608768 , 3.52371901, 3.48497958, 3.44451785, 3.4021735 ,
       3.35776278, 3.31107361, 3.26185951, 3.20983168, 3.15464877,
       3.09590327, 3.03310326, 2.96564727, 2.89278926, 2.81358809,
       2.72683303, 2.63092975, 2.52371901, 2.4021735 , 2.26185951,
       2.09590327, 1.89278926, 1.63092975, 1.26185951, 0.63092975])

* Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6. Use `arrange` and `sum` from numpy

In [164]:
# Define the rectangle width
width = 1e-6

# Create the sequence for the left endpoints (similar to seq in R)
x = np.arange(0, 1, width)

# Compute the sum using the left rectangle method
approximation = np.sum(x ** 2) * width

# Print the result
print(approximation)


0.33333283333349994


* Calculate the average of 100 realizations of standard Bernoullis in one line using the numpy's random.choice function.

In [165]:
mean_bern=np.mean(np.random.choice([0,1], size=100, replace=True))
mean_bern

0.5

* Calculate the average of 500 realizations of Bernoullis with p = 0.9 in one line using the `random.choice` and `mean` functions in numpy.

In [166]:
np.mean(np.random.choice([0,1], p=[0.1, 0.9], replace=True, size=500))

0.904

* Calculate the average of 1000 realizations of Bernoullis with p = 0.9 in one line using `binom` from scipy.stats.

In [170]:
from scipy.stats import binom
avg_bern=binom.rvs(n=1, p=0.9, size=1000).mean()
avg_bern

0.91

* Let `n = 50`. Create a n x n matrix `R` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [171]:
# Set n
n = 50

# Generate the random values with specified proportions
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the values into an n x n matrix
R = values.reshape(n, n)

# Convert the matrix into a DataFrame
df = pd.DataFrame(R)

# Print the DataFrame
print(df)

    0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0    2   2   0   2   0   1   1   1   0   0  ...   0   0   2   1   0   0   0   
1    2   0   1   0   2   2   2   2   2   0  ...   0   1   0   1   0   0   2   
2    0   0   0   1   0   0   2   1   0   2  ...   2   1   0   0   1   0   0   
3    0   0   2   1   1   0   0   1   2   0  ...   1   2   0   0   0   1   1   
4    2   0   0   1   0   2   0   0   0   2  ...   0   1   0   2   0   1   0   
5    1   2   1   0   1   2   0   0   1   0  ...   1   1   0   0   0   0   2   
6    1   0   1   0   2   0   0   0   2   1  ...   2   0   2   0   0   1   0   
7    2   1   0   1   0   0   0   2   2   2  ...   1   0   1   1   0   0   0   
8    0   1   1   0   1   0   2   2   1   1  ...   0   0   0   0   1   0   0   
9    1   0   2   1   0   2   0   0   0   0  ...   0   0   0   2   0   2   2   
10   1   0   0   2   1   0   0   2   0   0  ...   1   0   0   2   1   0   0   
11   0   2   0   2   0   1   2   1   0   0  ...   0 

* Randomly punch holes (i.e. `NA`) values in this matrix so that an each entry is missing with probability 30%.

In [172]:
# Convert to float to allow NaN
df = df.astype(float)

# Randomly punch holes with 30% probability
mask = np.random.choice([True, False], size=df.shape, p=[0.3, 0.7])
df[mask] = np.nan

# View the resulting DataFrame
print(df)

     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   2.0  2.0  NaN  2.0  0.0  1.0  NaN  NaN  0.0  NaN  ...  0.0  0.0  2.0  NaN   
1   2.0  0.0  NaN  0.0  2.0  2.0  NaN  2.0  2.0  NaN  ...  NaN  1.0  0.0  NaN   
2   NaN  0.0  0.0  NaN  NaN  NaN  NaN  1.0  NaN  2.0  ...  NaN  1.0  0.0  0.0   
3   0.0  0.0  2.0  NaN  1.0  0.0  0.0  NaN  2.0  NaN  ...  NaN  NaN  NaN  NaN   
4   NaN  0.0  0.0  NaN  0.0  2.0  0.0  NaN  NaN  2.0  ...  0.0  1.0  0.0  2.0   
5   1.0  2.0  NaN  0.0  1.0  2.0  0.0  0.0  NaN  0.0  ...  1.0  1.0  NaN  NaN   
6   1.0  0.0  NaN  0.0  2.0  0.0  0.0  NaN  2.0  1.0  ...  NaN  0.0  2.0  0.0   
7   2.0  NaN  NaN  1.0  0.0  NaN  0.0  2.0  2.0  2.0  ...  NaN  0.0  NaN  NaN   
8   NaN  NaN  1.0  NaN  1.0  NaN  2.0  2.0  1.0  1.0  ...  0.0  NaN  NaN  NaN   
9   NaN  0.0  2.0  NaN  NaN  2.0  0.0  NaN  0.0  NaN  ...  0.0  0.0  0.0  2.0   
10  NaN  NaN  NaN  2.0  1.0  NaN  0.0  2.0  0.0  0.0  ...  NaN  NaN  0.0  2.0   
11  0.0  NaN  0.0  NaN  0.0 

In [173]:
# Set matrix dimensions and proportions
n = 50
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the matrix
R = values.reshape(n, n)

# Create a mask for punching holes with a 30% probability
random_holes = np.random.choice([True, False], size=(n, n), p=[0.3, 0.7])

# Assign NaN to the corresponding positions
R = R.astype(float)  # Convert to float to support NaN
R[random_holes] = np.nan

# Convert to DataFrame
df = pd.DataFrame(R)


print(df)


     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   NaN  1.0  0.0  NaN  NaN  NaN  1.0  2.0  NaN  0.0  ...  0.0  0.0  0.0  NaN   
1   NaN  NaN  NaN  0.0  NaN  1.0  2.0  0.0  NaN  0.0  ...  1.0  2.0  0.0  NaN   
2   2.0  0.0  0.0  NaN  NaN  NaN  0.0  2.0  NaN  NaN  ...  1.0  0.0  1.0  NaN   
3   2.0  NaN  2.0  0.0  0.0  1.0  NaN  NaN  NaN  1.0  ...  0.0  0.0  NaN  0.0   
4   NaN  2.0  NaN  NaN  0.0  0.0  0.0  1.0  NaN  1.0  ...  0.0  0.0  NaN  1.0   
5   NaN  0.0  2.0  NaN  0.0  NaN  0.0  1.0  NaN  0.0  ...  1.0  NaN  NaN  2.0   
6   0.0  0.0  0.0  NaN  2.0  0.0  1.0  NaN  0.0  1.0  ...  0.0  0.0  1.0  0.0   
7   NaN  1.0  1.0  NaN  2.0  NaN  0.0  0.0  0.0  NaN  ...  2.0  NaN  0.0  2.0   
8   2.0  2.0  2.0  NaN  0.0  NaN  2.0  NaN  0.0  1.0  ...  NaN  0.0  2.0  NaN   
9   0.0  1.0  2.0  0.0  2.0  1.0  1.0  2.0  0.0  0.0  ...  1.0  1.0  NaN  2.0   
10  1.0  2.0  1.0  NaN  1.0  2.0  0.0  NaN  0.0  0.0  ...  0.0  NaN  NaN  NaN   
11  1.0  NaN  0.0  NaN  0.0 

* Sort the rows in matrix `R` by the largest row sum to lowest. Be careful about the NA's!

In [174]:
#compute row sums, ignoring NaN values
row_sum=np.nansum(R, axis=1)

#get the row indices sorted by largest rowsum to smallest
row_sort = np.argsort(-row_sum)
row_sort

array([40, 20, 14,  5, 41, 26, 48,  7, 15, 30, 42, 44,  1,  6, 45,  9, 47,
       32, 27, 16, 17,  2, 23, 10, 37, 11, 29, 13, 34,  0, 33, 24,  8, 28,
       25, 39,  3, 21, 31, 18, 12, 46,  4, 49, 22, 38, 43, 36, 35, 19],
      dtype=int64)

* Python does not have an apply function. Instead use the nanstd function in numpy to calculate the standard devation of each column. Print them and combine then into a dataframe.

In [176]:
#compute row-wise and column-wise standard deviation
row_sd = np.nanstd(R, axis=1)
col_sd = np.nanstd(R, axis=0)

#combine the results into a dictionary
result = {"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()} 

#Print the results
print(result["row_sd"])
print(result["col_sd"])


row_sd_count = sum(~np.isnan(result["row_sd"]))
col_sd_count = sum(~np.isnan(result["col_sd"]))  # Count of valid values in col_sd

#Print the counts
print("Count of non-NaN values in row_sd:", row_sd_count)
print("Count of non-NaN values in col_sd:", col_sd_count)

[0.8422247684280209, 0.7752936520529368, 0.81967981553775, 0.8411874071229224, 0.8454843286542927, 0.8833308765689106, 0.8426193117902646, 0.9187391537607729, 0.8190839013800723, 0.8439143072757396, 0.8324830903589637, 0.9051717723725149, 0.7709571972554637, 0.9131223741405675, 0.8778452283278408, 0.866524697803308, 0.8202679477907445, 0.888015443881146, 0.7907630001770314, 0.7180219742846006, 0.8744746321952062, 0.6718812375489759, 0.7915448249319448, 0.7592027982620249, 0.7752936520529368, 0.7405919620773836, 0.8542809364414888, 0.888015443881146, 0.871207650381413, 0.7888273965266452, 0.8298826628866153, 0.8786992562500797, 0.8534606386520677, 0.7729918727608158, 0.7888273965266452, 0.6813851438692469, 0.7319250547113999, 0.7842895215030988, 0.7794197001831111, 0.8265564664839913, 0.8655798028268269, 0.8027894294360562, 0.8741060339889853, 0.7282010825376439, 0.8447886244908865, 0.8425917976695477, 0.7591617288906527, 0.7766431633476234, 0.8542809364414888, 0.886950134507582]
[0.803

* combine the results from the previous cell into a dataframe

In [177]:
sd_df=pd.DataFrame({"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()})
sd_df

row_sd    col_sd
0   0.842225  0.803055
1   0.775294  0.844789
2   0.819680  0.778215
3   0.841187  0.774975
4   0.845484  0.865709
5   0.883331  0.829156
6   0.842619  0.852733
7   0.918739  0.881595
8   0.819084  0.839825
9   0.843914  0.732347
10  0.832483  0.593816
11  0.905172  0.802246
12  0.770957  0.854816
13  0.913122  0.898979
14  0.877845  0.759162
15  0.866525  0.838740
16  0.820268  0.906675
17  0.888015  0.819892
18  0.790763  0.832483
19  0.718022  0.904026
20  0.874475  0.736058
21  0.671881  0.853879
22  0.791545  0.738596
23  0.759203  0.809224
24  0.775294  0.792588
25  0.740592  0.887096
26  0.854281  0.769005
27  0.888015  0.833905
28  0.871208  0.848659
29  0.788827  0.826105
30  0.829883  0.748019
31  0.878699  0.905172
32  0.853461  0.846318
33  0.772992  0.776136
34  0.788827  0.823529
35  0.681385  0.806548
36  0.731925  0.833029
37  0.784290  0.843914
38  0.779420  0.807678
39  0.826556  0.812404
40  0.865580  0.779321
41  0.802789  0.803157
42  0.874106  0.803157
43  0.728201  0.859995
44  0.844789  0.844145
45  0.842592  0.768013
46  0.759162  0.849803
47  0.776643  0.887096
48  0.854281  0.809909
49  0.886950  0.818879

* Use the Pandas apply function to compute a vector whose entries are the count of entries that are 1 or 2 in each column

In [178]:
R = pd.DataFrame(R)
#Compute the count of 1's and 2's in each column
counts = R.apply(lambda col: ((col == 1) | (col == 2)).sum(), axis=0)

#Print the counts
print(counts)

0     13
1     19
2     15
3     15
4     16
5     18
6     20
7     21
8     17
9     15
10    10
11    24
12    14
13    18
14    20
15    19
16    16
17    17
18    22
19    19
20    15
21    11
22    19
23    20
24    12
25    19
26    19
27    17
28    18
29    15
30    17
31    21
32    13
33    14
34    16
35    18
36    20
37    16
38    18
39    22
40    16
41    18
42    18
43    21
44    17
45    19
46    14
47    19
48    20
49    19
dtype: int64


Since we just switched between Pandas dataframes and Numpy arrays. Here are some handy ways to check to see if you are working with a Pandas dataframe or a Numpy array

In [179]:
# Check type directly
if type(R) == pd.DataFrame:
    print("R is a Pandas DataFrame")

if type(R) == np.ndarray:
    print("R is a NumPy array")

R is a Pandas DataFrame


In [180]:
# isinstance(object, classinfo): This function checks if an object is an instance of a specified class or subclass.
# function utilizing this function to check
def check_type(R):
    if isinstance(R, pd.DataFrame):
        return "Pandas DataFrame"
    elif isinstance(R, np.ndarray):
        return "NumPy array"
    else:
        return "Unknown type"

# Test the function
print(check_type(R))  # Output: Pandas DataFrame

Pandas DataFrame


* Create a list whose keys are the column number and values are the vector of the columns.

In [182]:
hm={}
for col in R.columns:
    hm[col]=(R[col].values).tolist()
print(hm)

{0: [nan, nan, 2.0, 2.0, nan, nan, 0.0, nan, 2.0, 0.0, 1.0, 1.0, 2.0, 0.0, 1.0, 0.0, 0.0, nan, 1.0, nan, 2.0, 0.0, nan, 2.0, 0.0, 0.0, 2.0, nan, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, nan, 0.0, nan, 0.0, 0.0, 0.0, nan, 0.0, 0.0, 0.0, 0.0, nan, nan, 0.0, nan, 0.0], 1: [1.0, nan, 0.0, nan, 2.0, 0.0, 0.0, 1.0, 2.0, 1.0, 2.0, nan, 0.0, 2.0, nan, 1.0, nan, 2.0, nan, 2.0, 2.0, 0.0, nan, 0.0, 2.0, 0.0, 1.0, 0.0, 0.0, nan, 2.0, nan, nan, 1.0, 1.0, nan, nan, 0.0, 0.0, 0.0, 2.0, nan, 0.0, 1.0, nan, 0.0, 1.0, 0.0, nan, nan], 2: [0.0, nan, 0.0, 2.0, nan, 2.0, 0.0, 1.0, 2.0, 2.0, 1.0, 0.0, 0.0, 2.0, nan, nan, 0.0, nan, 0.0, nan, 1.0, nan, nan, 1.0, 1.0, 0.0, nan, 0.0, 2.0, nan, 0.0, 0.0, nan, nan, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, nan, nan, nan, nan, 1.0, nan, 0.0, nan, nan], 3: [nan, 0.0, nan, 0.0, nan, nan, nan, nan, nan, 0.0, nan, nan, 1.0, 1.0, 2.0, nan, 0.0, 0.0, nan, nan, 2.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 1.0, nan, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, nan, nan, nan, 1.0, nan, 0.0, nan, 

* Create a list whose keys are the column number and values are themselves a list with keys: "min" whose value is the minimum of the column, "max" whose value is the maximum of the column, "pct_missing" is the proportion of missingness in the column and "first_NA" whose value is the row number of the first time the NA appears. In R this was accomplished using lappy. In Python we will use dictionary comprehension in tandem with Numpy and Pandas operations.

In [183]:
hm={}
for col in R.columns:
    #np array of col
    curr_col=R[col].values

    #mask method of removing nans
    mask= ~np.isnan(curr_col)
    nan_less_col=curr_col[mask]

    #create temp dict with keys and values
    temp={}
    temp["min"]=np.min(nan_less_col)
    temp["max"]=np.max(nan_less_col)
    temp["pct_missing"]=(len(curr_col)-len(nan_less_col)) / len(curr_col)

    #add temp dict to main dict
    hm[col]=temp
print(hm)

{0: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3}, 1: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32}, 2: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38}, 3: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.36}, 4: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26}, 5: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28}, 6: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.22}, 7: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26}, 8: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3}, 9: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32}, 10: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.34}, 11: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32}, 12: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28}, 13: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3}, 14: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3}, 15: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.22}, 16: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38}, 17: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.4}, 18: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.38}, 19: {'min': 0.0, 'max': 2.0, 'pct_missing': 0

* Set a seed and then create a vector `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [185]:
#set seed
np.random.seed(343)

#draw iid normal with mean -10 and sd of 10 (variance 100)
v = np.random.normal(loc=[-10], scale=[10], size=1000)
print(v)

[-7.87551704e+00 -1.61826621e+01 -1.93192949e+01  8.21476003e+00
 -8.38698341e+00 -1.09994008e+01 -1.20084892e+01 -1.22613009e+01
 -1.35583980e+01 -8.13913280e+00  2.69733548e+00  1.05604888e+00
 -7.37103870e+00 -1.23985848e+01 -1.43841626e+01 -4.32643181e+00
 -2.81589371e+01 -2.18343002e+00 -1.95733970e+01 -1.22571036e+00
 -1.31261729e+01 -7.29294192e+00  5.41322607e+00  1.47363152e+00
 -2.14149095e+01 -1.10069451e+01 -2.30644877e+01 -1.19148184e+01
 -9.50641374e-02 -3.85781294e+00 -1.19067285e+01 -2.75351774e+01
  1.93042715e+00 -5.37629128e+00 -9.95572806e+00 -4.73656958e+00
  1.35252498e+01 -9.94233488e+00 -2.03682477e+01 -1.48897252e+01
 -1.07649779e-01 -1.37489460e+01 -5.04401563e+00 -2.02389977e+00
 -3.34829152e+01 -1.51976690e+01 -2.14008183e+01 -1.08031027e+01
 -1.56434662e+01 -1.86236534e+00 -1.73256089e+01  7.29557451e+00
 -1.65767023e+01 -1.92255870e+01 -2.92522274e+01  2.44478098e+00
 -4.75730139e+00 -1.13946497e+01 -1.06785214e+01 -7.03452549e+00
 -1.00782290e+01  3.15636

* Repeat this exercise by resetting the seed to ensure you obtain the same results. You can use the random module built in python or random.seed from numpy.

In [186]:
#set seed
np.random.seed(343)

#draw iid normal with mean -10 and sd of 10 (variance 100)
v = np.random.normal(loc=[-10], scale=[10], size=1000)
print(v)

[-7.87551704e+00 -1.61826621e+01 -1.93192949e+01  8.21476003e+00
 -8.38698341e+00 -1.09994008e+01 -1.20084892e+01 -1.22613009e+01
 -1.35583980e+01 -8.13913280e+00  2.69733548e+00  1.05604888e+00
 -7.37103870e+00 -1.23985848e+01 -1.43841626e+01 -4.32643181e+00
 -2.81589371e+01 -2.18343002e+00 -1.95733970e+01 -1.22571036e+00
 -1.31261729e+01 -7.29294192e+00  5.41322607e+00  1.47363152e+00
 -2.14149095e+01 -1.10069451e+01 -2.30644877e+01 -1.19148184e+01
 -9.50641374e-02 -3.85781294e+00 -1.19067285e+01 -2.75351774e+01
  1.93042715e+00 -5.37629128e+00 -9.95572806e+00 -4.73656958e+00
  1.35252498e+01 -9.94233488e+00 -2.03682477e+01 -1.48897252e+01
 -1.07649779e-01 -1.37489460e+01 -5.04401563e+00 -2.02389977e+00
 -3.34829152e+01 -1.51976690e+01 -2.14008183e+01 -1.08031027e+01
 -1.56434662e+01 -1.86236534e+00 -1.73256089e+01  7.29557451e+00
 -1.65767023e+01 -1.92255870e+01 -2.92522274e+01  2.44478098e+00
 -4.75730139e+00 -1.13946497e+01 -1.06785214e+01 -7.03452549e+00
 -1.00782290e+01  3.15636

* Find the average of `v` and the standard error of `v`.

In [187]:
v_mean = np.mean(v)
v_sd = np.std(v)

print(v_mean)
print(v_sd)

-9.723988808367439
10.186388231081471


* Find the 5%ile of `v` and use the `norm` function from scipy.stats to compute what it theoretically should be. Is the estimate about what is expected by theory?

In [189]:
from scipy.stats import norm

realized = np.percentile(v, 5)
theoretical = norm.ppf(0.05, loc=-10, scale=10)

print(realized)
print(theoretical)

#Yes it's about as expected

-26.35587956614618
-26.44853626951473


* What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?

In [190]:
#its about 1 sd above the mean so i'd expect a value close to 85

#set values less than (0) to 1
v_leq_0 = np.where(v<=0, 1, 0)

#get percentage of values below (0)
v_0_real = (np.sum(v_leq_0)/len(v))*100

#percentile of 0 in this dist.
theoretical = norm.cdf(0, loc=-10, scale=10)

print(v_0_real)
print(theoretical * 100)

#Yes this is about as expected

83.1
84.1344746068543


* Create a function `my_reverse` which takes as required input a vector `v` and returns the vector in reverse where the first entry is the last entry, etc. No function calls are allowed inside your function otherwise that would defeat the purpose of the exercise! (Yes, there is a base R function that does this called `rev`). 

In [192]:
def my_reverse(v):
    v_reversed = v[::-1]
    return v_reversed

 * Built in methods in python to reverse a list.

In [193]:
#reverse using slicing
v = [1, 2, 3, 4, 5]
v_reversed = v[::-1]
print(v_reversed)

#using the .reverse method
v = [1, 2, 3, 4, 5]
v.reverse()
print(v)

[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


* Create a function `flip_matrix` which takes as required input a matrix, an argument `dim_to_rev` that returns the matrix with the rows in reverse order or the columns in reverse order depending on the `dim_to_rev` argument. Let the default be the dimension of the matrix that is greater.

In [194]:
#function that flips matrix on dim_to_rev axis
def flip_matrix(matrix, dim_to_rev="col"):
    if(dim_to_rev=="row"):
        return matrix[::-1]
    else:
        return matrix[:,::-1]

m=np.array([[0,1,2],[3,4,5],[6,7,8]])   #create matrix

#print matrix, matrix flipped by column, matrix flipped by row
print(m)
print(flip_matrix(m,"col"))
print(flip_matrix(m,"row"))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


* Create a list named `my_list` with keys "A", "B", ... where the entries are arrays of size 1, 2 x 2, 3 x 3 x 3, etc. Fill the array with the numbers 1, 2, 3, etc. Make 8 entries according to this sequence.

In [195]:
my_list={}

#create list of keys
keys=["A","B","C","D","E","F","G","H"]

for i in range(1, 9):
    #pair key with matrix full of respective value
    my_list[keys[i-1]]=np.full((i,i),i)

my_list

{'A': array([[1]]),
 'B': array([[2, 2],
        [2, 2]]),
 'C': array([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]),
 'D': array([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]),
 'E': array([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]),
 'F': array([[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]]),
 'G': array([[7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7]]),
 'H': array([[8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8, 8, 8],
        

* Run the following code:

In [196]:
import sys

sizes = {key: sys.getsizeof(value) for key, value in my_list.items()}


# Print the sizes
for key, size in sizes.items():
    print(f"Key: {key}, Size: {size} bytes")

Key: A, Size: 132 bytes
Key: B, Size: 144 bytes
Key: C, Size: 164 bytes
Key: D, Size: 192 bytes
Key: E, Size: 228 bytes
Key: F, Size: 272 bytes
Key: G, Size: 324 bytes
Key: H, Size: 384 bytes


* Create vector `v` consisting of all numbers from -100 to 100 and test using the second line of code

In [197]:
v=np.arange(-100, 101)
print(v)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    0    1    2    3    4    5    6    7    8    9   10   11
   12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   37   38   39
   40   41   42   43   44   45   46   47   48   49   50   51   52   53
   54   55   56   57   58   59   60   61   62   63   64   65   66   67
   68   69   70   71   72   73   74   75   76   77   78   79   80   81
   82   83   84   85   86   87   88   89   90   91   92   93   94   95
   96 

* Test the `my_reverse` function using the following code:

In [198]:
# Test the function
v = list(range(1, 11))
v_reversed = my_reverse(v)
print(v)
print(v_reversed)
type(v_reversed)

assert my_reverse(v) == v[::-1], "my_reverse failed for numerical vector"

 # Test with character vector
v_char = ["A", "B", "C"]
assert my_reverse(v_char) == v_char[::-1], "my_reverse failed for character vector"

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## A little about strings

* Use the `re.split` function by importing the re module and `random` from the random module to put the sentences in the string `lorem` below in random order. You will also need to manipulate the output of `re.split` which is a list. You may need to learn basic concepts of regular expressions.

In [199]:
import re
import random

lorem = """Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi posuere varius volutpat. Morbi faucibus ligula id massa ultricies viverra.
Donec vehicula sagittis nisi non semper. Donec at tempor erat.
Integer dapibus mi lectus, eu posuere arcu ultricies in.
Cras suscipit id nibh lacinia elementum. Curabitur est augue, congue eget quam in, scelerisque semper magna.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu. Mauris at sodales augue."""

#split sentence by period
sentence_split=re.split(r"\. ", lorem)

#shuffle the list of sentences
random.shuffle(sentence_split)

#join the list to a string
shuffled_lorem=" ".join(sentence_split)

print(shuffled_lorem)

Morbi faucibus ligula id massa ultricies viverra.
Donec vehicula sagittis nisi non semper Curabitur est augue, congue eget quam in, scelerisque semper magna.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi posuere varius volutpat Donec at tempor erat.
Integer dapibus mi lectus, eu posuere arcu ultricies in.
Cras suscipit id nibh lacinia elementum Mauris at sodales augue.


* You have a set of names divided by gender (M / F) and generation (Boomer / GenX / Millenial):

M / Boomer      "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"

M / GenX        "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"

M / Millennial  "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis"

F / Boomer      "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"

F / GenX        "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"

F / Millennial  "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne"

Create python dictionary to store this data.


In [201]:
#create a dict for men where key is generation and value is list of names
males={}
males["Boomer"] = ["Theodore", "Bernard", "Gene", "Herbert", "Ray", "Tom", "Lee", "Alfred", "Leroy", "Eddie"]
males["Genx"] = ["Marc", "Jamie", "Greg", "Darryl", "Tim", "Dean", "Jon", "Chris", "Troy", "Jeff"]
males["Millennial"] = ["Zachary", "Dylan", "Christian", "Wesley", "Seth", "Austin", "Gabriel", "Evan", "Casey", "Luis"]

#create a dict for women where key is generation and value is list of names
females={}
females["Boomer"] = ["Gloria", "Joan", "Dorothy", "Shirley", "Betty", "Dianne", "Kay", "Marjorie", "Lorraine", "Mildred"]
females["Genx"] = ["Tracy", "Dawn", "Tina", "Tammy", "Melinda", "Tamara", "Tracey", "Colleen", "Sherri", "Heidi"]
females["Millennial"] = ["Samantha", "Alexis", "Brittany", "Lauren", "Taylor", "Bethany", "Latoya", "Candice", "Brittney", "Cheyenne"]

#create a dict where key is gender (M or F) and value is dict of names by generation
gender_generation_name_hm={"M":males, "F":females}

print(gender_generation_name_hm)

{'M': {'Boomer': ['Theodore', 'Bernard', 'Gene', 'Herbert', 'Ray', 'Tom', 'Lee', 'Alfred', 'Leroy', 'Eddie'], 'Genx': ['Marc', 'Jamie', 'Greg', 'Darryl', 'Tim', 'Dean', 'Jon', 'Chris', 'Troy', 'Jeff'], 'Millennial': ['Zachary', 'Dylan', 'Christian', 'Wesley', 'Seth', 'Austin', 'Gabriel', 'Evan', 'Casey', 'Luis']}, 'F': {'Boomer': ['Gloria', 'Joan', 'Dorothy', 'Shirley', 'Betty', 'Dianne', 'Kay', 'Marjorie', 'Lorraine', 'Mildred'], 'Genx': ['Tracy', 'Dawn', 'Tina', 'Tammy', 'Melinda', 'Tamara', 'Tracey', 'Colleen', 'Sherri', 'Heidi'], 'Millennial': ['Samantha', 'Alexis', 'Brittany', 'Lauren', 'Taylor', 'Bethany', 'Latoya', 'Candice', 'Brittney', 'Cheyenne']}}


* Now cleanup the namespace by deleting all stored objects and functions:

In [126]:
%reset